In [1]:
1

1

In [7]:
import pandas as pd
import numpy as np

In [6]:
"""
hum kaise simply different data sources se file
read karenge and file bhi specifically konsi hogi
, separated waali jo file hogi
usko read karna dekhenge"""

cs =pd.read_csv('cars.csv')

In [7]:
cs

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [8]:
cs.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
cs[1:,2]

InvalidIndexError: (slice(1, None, None), 2)

In [10]:
cs.iloc[1:,2:]

        fuel                 owner  selling_price
1     Diesel          Second Owner         370000
2     Petrol           Third Owner         158000
3     Diesel           First Owner         225000
4     Petrol           First Owner         130000
5     Petrol           First Owner         440000
...      ...                   ...            ...
8123  Petrol           First Owner         320000
8124  Diesel  Fourth & Above Owner         135000
8125  Diesel           First Owner         382000
8126  Diesel           First Owner         290000
8127  Diesel           First Owner         290000

[8127 rows x 3 columns]

In [11]:
type(cs)

pandas.DataFrame

In [ ]:
"""jab hum simply read karte hai csv to hume pehle to simply datasource ,separator ke alava bhi bhot saare argument hote simply
lets create simply a new data set"""

'jab hum simply read karte hai csv to hume pehle to simply datasource ,separator ke alava bhi bhot saare argument hote simply'

In [4]:
data=('col1,col2,col3\n'
'x,y,1\n'
'a,b,2\n'
'c,j,4')

"""simply agar hum data define karte and when we check type of the data wo simply string and agar direct 
hum read karne ka try kare to wo error throw karega is case me hume particular data jo hai wo memory me loaded chaiye
hota hai aur us case me IO use karte hai"""
type(data)

str

In [2]:
from io import StringIO

In [5]:
dataforporcess=StringIO(data)

In [29]:
pss=pd.read_csv(dataforporcess)

In [30]:
pss

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    j     4

In [9]:
"""
agar simply hum specific columns use karna hai to hum simply 
usecols use karenge """

prr=pd.read_csv(dataforporcess,usecols=['col1','col2'])

In [10]:
prr

  col1 col2
0    x    y
1    a    b
2    c    j

In [ ]:
prr.to_csv('new_csv') #using this we can create a new csv file and save it  in the current directory

In [16]:
"""while reading the csv file we can also specify the datatype should be considered for each column
using dtype
"""

df=pd.read_csv(StringIO(data),dtype='object')
df.info

<bound method DataFrame.info of   col1 col2 col3
0    x    y    1
1    a    b    2
2    c    j    4>

In [18]:
"""agar hume aisa karna hai to hum simply isko bhi aisa kar sakte hai ki hum specific columns ke liye datatype bhi set kar sakte hai ye karne ke liye hume simply dictionary use kar sakte hai specific column ke liye specific value set karne ke liye"""

df=pd.read_csv(StringIO(data),dtype={'col1':'str','col2':'str','col3':'int'})

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      str
 1   col2    3 non-null      str
 2   col3    3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 210.0 bytes