In [2]:
"""Pandas library bhot jyada important hai simply learning purpose se dekhne gaye agar hum data analytics ya fir data scientist ya fir data ka 
ke saath kehlna hai csv file ke saath khelna hai to hume data ko sabse pehle dataframe me convert karna padta hai and then simply wo jo data frame hote hai 
wo hum pandas ki library ke use se kar sakte hai 

step1 pandas dataframes , pandas series , pandas basic operations"""


import pandas as ps
import numpy as np

In [7]:
## Create Dataframe
"""
data frame create karte samay simply hume kuch parameter pass karne hote taaki sucessfully hum data frame bana sake
sabse pehla hota hai data, uske baad index dena hota index dene ke baad hume column ka naam bhi dena hota hai simply
jisko hum column name kehte hai """

arr= np.arange(0,20).reshape(5,4)
df=ps.DataFrame(arr,index=["ROW1","ROW2","ROW3","ROW4","ROW5"],columns=["Column1","Column2","Column3","Column4"])

In [ ]:
#agar hume top five records dekhna hai to hum .head() function ka use kar sakte hai hume jitna record dekhna hai bas wo as a argument pass karna hai 
df.head()

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [12]:
#tail function pandas ka aisa function hai jo ki simply use hota hai last ke 5 record dekhne ke liye agar hume usme last 5 se jyada dekhna hai to hume simply pass karna padta hai particular number as a argument
df.tail(3)

      Column1  Column2  Column3  Column4
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [13]:
type(df)

pandas.DataFrame

In [15]:
df.info() # simply info function ka use karke hum simply column ka data type kya hai wo pata kar sakte hai simply

<class 'pandas.DataFrame'>
Index: 5 entries, ROW1 to ROW5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 220.0 bytes

In [18]:
#agar hume column ke stats ke baare me jaanna hai to hum simply describe ka use karte hai
df.describe()

         Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [19]:
##indexing 
""" indexing hum 2 tarike se use kar sakte hai simply
ek to simply columnname ka use karke aur ek to rowindex ka use karke bur row index ke andar hume simply loc ka bhi use karna hota hai
third strategy hai rowindex number column index number[.iloc]"""

df.head()

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [21]:
df[['Column1','Column2','Column3']]

      Column1  Column2  Column3
ROW1        0        1        2
ROW2        4        5        6
ROW3        8        9       10
ROW4       12       13       14
ROW5       16       17       18

In [ ]:
#AGAR SIRF FIRST COLUMN KA USE KARKE KARNA HAI 
"""agar major difference pata karna hai series and dataframes in pandas to wo hai ki 
dataframes me more than one row or column hume select hi karna hota hai jabki 
series me ulta hai either one row or either one column hume select karna hota hai """

df['Column1']

ROW1     0
ROW2     4
ROW3     8
ROW4    12
ROW5    16
Name: Column1, dtype: int64

In [26]:
#rowindex location ka use karke accessing the value
df.loc[['ROW1','ROW2']]

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7

In [ ]:


df.head()

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [ ]:
 #Third technique simply dono index ko hum simply combine kar sakte hai left ka jo number hai wo row number hai and right ka jo hai wo column number hai
 
 df.iloc[2:4,0:2]

      Column1  Column2
ROW3        8        9
ROW4       12       13

In [32]:
df.iloc[2:,1:]

      Column2  Column3  Column4
ROW3        9       10       11
ROW4       13       14       15
ROW5       17       18       19

In [33]:
#agar hume dataframes se arrays me convert karna hai to hum .values ka use kar sakte hai simply 
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [34]:
# basic operation
df

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [37]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [41]:
ds=ps.DataFrame(data=[[1,np.nan,2],[1,2,3]],index=["Row1","Row2"],columns=["Column1","Column2","Column3"])

In [44]:
ds.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [43]:
ds

      Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      2.0        3

In [45]:
ds.value_counts

<bound method DataFrame.value_counts of       Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      2.0        3>

In [47]:
# simply ye batata hai ki konsi value kitne baar present hai simply
ds["Column1"].value_counts()

Column1
1    2
Name: count, dtype: int64

In [48]:
ds['Column2'].unique()

array([nan,  2.])

In [51]:
df.Column2.value_counts()

Column2
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [54]:
df>2
df

      Column1  Column2  Column3  Column4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [53]:
df[df["Column1"]>2]

      Column1  Column2  Column3  Column4
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19